<a href="https://colab.research.google.com/github/Joehersh1998/Hersh-690-HW-4/blob/main/Hershberger_Final_Project_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Research Question**

This research project examines the effect that setting a minimum wage has on a state, specifically the unemployment and poverty rates. This study will explore whether higher and lower minimum wages have an overall positive or negative effect on a state's economy. Specifically, do they improve the state's economy by reducing poverty or have a negative effect by increasing unemployment?

Opponents of raising the minimum wage argue that the increased labor market costs force businesses to reduce hiring or lay off workers, which could lead to higher unemployment. They also say that increasing the minimum wage has little effect on reducing poverty because businesses would have to reduce hiring. Supporters on the other hand, argue that higher minimum wages help lift workers out of poverty by increasing earnings for low-income households. They also argue that higher wages increase consumer spending, which can stimulate economic growth and, as a result of that increase employment.



My research question is: Do states with higher minimum wages experience lower poverty rates but higher unemployment rates?

**Data Cleaning **

In [ ]:
import pandas as pd
import seaborn as sns

This data shows the minimum wage for each state in the year 2026. It is collected from the Federal Reserve Economic Data website.

In [ ]:
url = "https://fred.stlouisfed.org/release/tables?eid=243906&rid=387"

tables = pd.read_html(url)

mw = tables[0]

In [ ]:
mw.columns = [
    "id",
    "State",
    "Period",
    "minimum_wage",
    "previous_period",
    "year_ago"
]

In [ ]:
mw_2026 = mw[mw["Period"] == "2026"].copy()

mw_2026 = mw_2026[["State", "minimum_wage"]]

mw_2026["minimum_wage"] = pd.to_numeric(
    mw_2026["minimum_wage"]
)

In [ ]:
len(mw_2026)

48

In [ ]:
missing_states = pd.DataFrame({
    "State": [
        "Alabama",
        "Georgia",
        "Louisiana",
        "Mississippi",
        "South Carolina",
        "Tennessee",
        "Wyoming"
    ],
    "minimum_wage": [7.25] * 7
})

mw_2026 = pd.concat(
    [mw_2026, missing_states],
    ignore_index=True
)

In [ ]:
mw_2026 = mw_2026[
    ~mw_2026["State"].isin([
        "Federal Minimum Wage Rate",
        "District of Columbia",
        "Guam",
        "Puerto Rico",
        "U.S. Virgin Islands"
    ])
]

In [ ]:
len(mw_2026)

50

In [ ]:
mw_2026.head(15)

          State  minimum_wage
1        Alaska         13.00
2      Arkansas         11.00
3       Arizona         15.15
4    California         16.90
5      Colorado         15.16
6   Connecticut         16.94
7      Delaware         15.00
8       Florida         14.00
9        Hawaii         16.00
10         Iowa          7.25
11        Idaho          7.25
12     Illinois         15.00
13      Indiana          7.25
14       Kansas          7.25
15     Kentucky          7.25

The first step of this process was to scrape the minimum wage table directly from the website. Because the webpage contained multiple tables, the first table was selected and stored as a pandas data frame for further cleaning. The variables were then renamed to make the dataset easier to understand. The new variable names identified the state, year, minimum wage, previous value, and year-ago value. After renaming the variables, I decided that I only needed observations from 2026, since this study focuses on the current minimum wage policies for each state. So I cleaned the dataset further to only include the state name and the minimum wage for that specific state. After that, I converted minimum wage values to numeric variables.

After completing these steps and running a quick check, I noticed that there were several states that did not report a state minimum wage because they followed the federal minimum wage of $7.25 per hour. To fix this, I manually added these states with their minimum wages. Finally, the dataset included several observations that were not U.S. states, including the District of Columbia and several U.S. territories. Because I wanted to solely focus on just the 50 states, I removed them from the dataset. This then produced a complete state-level minimum wage dataset.

This data was collected through the World Population Review website.

---

In [ ]:
url = "https://worldpopulationreview.com/state-rankings/poverty-rate-by-state"

tables = pd.read_html(url)

poverty = tables[0]

In [ ]:
poverty = poverty[
    ["State", "% Of Population Below Poverty Level↓"]
]

In [ ]:
poverty.columns = [
    "State",
    "poverty_rate"
]

In [ ]:
poverty["poverty_rate"] = (
    poverty["poverty_rate"]
    .str.replace("%", "", regex=False)
)

/tmp/ipykernel_11576/2350656436.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty["poverty_rate"] = (

In [ ]:
poverty["poverty_rate"] = pd.to_numeric(
    poverty["poverty_rate"]
)

/tmp/ipykernel_11576/2979206075.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  poverty["poverty_rate"] = pd.to_numeric(

In [ ]:
poverty = poverty[
    ~poverty["State"].isin([
        "District of Columbia",
        "Puerto Rico"
    ])
]

In [ ]:
poverty = poverty[
    poverty["State"] != "United States"
]

In [ ]:
len(poverty)

50

Like the minimum wage data, the first step I did in this process was to scrape the poverty table directly from the webpage and into Python. The first table on the webpage contained state-level poverty statistics and was stored in the data frame named poverty. The original dataset contained several variables that were not needed for this study, so I removed all of them with the exception of state name and the percentage of the population that were living below the poverty line. The poverty rate variables also had long and difficult-to-use column names. Therefore, those variables were renamed to State and poverty_rate to improve readability and make the dataset easier to work with. The poverty rate values were originally stored as text because they included percentage symbols. The percentage signs were removed from each observation, and the variable was converted into a numeric data type.

This data was colllected through the USA symbol website, which provides recent state-level unemployment numbers.

In [ ]:
url = "https://usasymbol.com/rankings/economy/states-by-unemployment"

tables = pd.read_html(url)

unemployment = tables[0]

In [ ]:
unemployment = unemployment[
    ["State", "Unempl. Rate"]
]

In [ ]:
unemployment.columns = [
    "State",
    "unemployment_rate"
]

In [ ]:
unemployment["unemployment_rate"] = (
    unemployment["unemployment_rate"]
    .astype(str)
    .str.replace("%", "", regex=False)
)

/tmp/ipykernel_11576/3817632299.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unemployment["unemployment_rate"] = (

In [ ]:
unemployment["unemployment_rate"] = pd.to_numeric(
    unemployment["unemployment_rate"]
)

/tmp/ipykernel_11576/4143310828.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  unemployment["unemployment_rate"] = pd.to_numeric(

In [ ]:
len(unemployment)

50

Similar to the other two datasets, the first step in this process was to scrape the unemployment table directly from the webpage and import it into Python. The table contained state-level unemployment statistics and was stored in the data frame unemployment. The original table also contained information that was not needed, and because of that I removed all the unnecessary information, only leaving the state name and unemployment rate variables.
The unemployment rate variable was renamed to unemployment_rate to create a shorter variable name. The unemployment rates were originally stored as text because the values included percentage symbols. Therefore, the percentage signs were removed, and the variable was converted to a numeric data type. I also kept the state variable, as I knew that I was going to need it later on to merge all three datasets.

In [ ]:
df = mw_2026.merge(
    poverty,
    on="State"
)

df = df.merge(
    unemployment,
    on="State"
)

len(df)

50

Once I finished cleaning all the three datasets, I merged them using the state name as the common identifier. Combining the datasets created a single state-level dataset that contained all the variables that are needed for the analysis. The final dataset includes observations for all 50 states including the minimum wage for that state, the poverty rate of that state, and the unemployment rate of the state.

In [ ]:
df.head(50)

             State  minimum_wage  poverty_rate  unemployment_rate
0           Alaska        13.000          10.5                4.8
1         Arkansas        11.000          16.3                4.2
2          Arizona        15.150          12.8                4.3
3       California        16.900          12.3                5.5
4         Colorado        15.160           9.7                3.8
5      Connecticut        16.940          10.1                4.2
6         Delaware        15.000          11.6                5.2
7          Florida        14.000          13.1                4.3
8           Hawaii        16.000          11.2                2.2
9             Iowa         7.250          11.1                3.5
10           Idaho         7.250          11.0                3.6
11        Illinois        15.000          12.1                4.6
12         Indiana         7.250          12.2                3.5
13          Kansas         7.250          11.7                3.8
14        Kentucky         7.250          16.5                4.5
15   Massachusetts        15.000          10.4                4.8
16        Maryland        15.000          10.3                4.2
17           Maine        15.100          11.5                3.2
18        Michigan        13.730          13.1                4.5
19       Minnesota        11.410           9.3                4.1
20        Missouri        15.000          12.7                3.9
21         Montana        10.853          11.9                3.4
22  North Carolina         7.250          13.4                3.9
23    North Dakota         7.250          11.1                2.6
24        Nebraska        15.000          10.8                3.0
25   New Hampshire         7.250           7.2                3.1
26      New Jersey        15.920          10.2                5.4
27      New Mexico        12.000          18.4                4.3
28          Nevada        12.000          14.1                5.2
29        New York        17.000          13.9                4.6
30            Ohio        11.000          13.4                4.5
31        Oklahoma         7.250          15.6                3.6
32          Oregon        16.300          12.2                5.2
33    Pennsylvania         7.250          12.1                4.2
34    Rhode Island        16.000          11.4                4.3
35    South Dakota        11.850          12.3                2.2
36           Texas         7.250          14.2                4.3
37            Utah         7.250           8.6                3.6
38        Virginia        12.770          10.2                3.6
39         Vermont        14.420          10.3                2.6
40      Washington        17.130           9.9                4.7
41       Wisconsin         7.250          10.8                3.1
42   West Virginia         8.750          16.8                4.6
43         Alabama         7.250          16.1                2.7
44         Georgia         7.250          14.0                3.6
45       Louisiana         7.250          19.6                4.2
46     Mississippi         7.250          19.4                3.4
47  South Carolina         7.250          14.6                4.8
48       Tennessee         7.250          13.6                3.6
49         Wyoming         7.250          11.4                3.4

In [ ]:
df.to_csv(
    "minimum_wage_project_data.csv",
    index=False
)

In [ ]:
import os
os.listdir()

['.config',
 'Hershberger Final Project 1.csv',
 'minimum_wage_project_data.csv',
 'sample_data']

In [ ]:
from google.colab import files

files.download(
    "minimum_wage_project_data.csv"
)